
platform :ios, '7.0'

inhibit_all_warnings!

pod 'AFNetworking', '~> 3.0.0-beta.1'   # AFNetworking
pod 'ReactiveCocoa', '~> 2.5'           # ReactiveCocoa
pod 'FDFullscreenPopGesture', '~> 1.1'  # 滑动返回的类目优点：从无导航栏到有导航栏的相互滑动效果都OK，没发现bug，缺点：松手后的动画没有（知乎的动画效果）github中 XXViewController 框架是有松手后的动画的，还有自己的项目宅家送（Budder）也可以。
pod 'CYLTabBarController', '~> 1.0.5'   # 不错的自定义tabbar
pod 'SDWebImage', '~> 3.7.3'

#—————————————暂时不用的———————————————————————

#pod 'CKViewPager', '~> 2.0.6'           # 左右滑动控制器。离线地图用的。——暂时不用

#pod 'ZMWImagePicker', '~> 1.0.6'

#pod 'YYKit', '~> 0.9.4'

#pod 'ZMWImageCache', '~> 1.1.0'

#pod 'Mapbox-iOS-SDK', '~> 3.0.0'

#pod 'CocoaLumberjack', '~> 2.0.0'       # CocoaLumberjack.

#pod 'FMDB', '~> 2.5'                    # FMDB
#pod 'Masonry', '~> 0.6.2'               # MasonryAutoLayout
#pod 'YYCache', '~> 0.9.1'              # 类似NSCache 比NSCache更好。
#pod 'YYWebImage', '~> 0.9.8'            # YY的image框架。
